apiVersion: v1
kind: Service
metadata:
  labels:
    app: csvserver
  name: csvserver
spec:
  ports:
  - name: csvserver
    port: 80
    protocol: TCP
    targetPort: 9300
  selector:
    app: csvserver
  type: ClusterIP
